### 1 Dimensional Numpy Array
#### <font color='red'> "Vectors - 1D" </font>

In [26]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)
print("shape: {}".format(a.shape))
print("size: {}".format(a.size))
print("ndim: {}".format(a.ndim))
print("dtype: {}".format(a.dtype))
print("len(): {}".format(len(a)))

[ 1  2  3  4  5  6  7  8  9 10]
shape: (10,)
size: 10
ndim: 1
dtype: int32
len(): 10


### 2 Dimensional Numpy Array
#### <font color='red'> "Matrices - 2D" </font>

In [27]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[10, 11, 12]])
print(b)
print("shape: {}".format(b.shape))
print("size: {}".format(b.size))
print("ndim: {}".format(b.ndim))
print("dtype: {}".format(b.dtype))
print("len(): {}".format(len(b)))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
shape: (4, 3)
size: 12
ndim: 2
dtype: int32
len(): 4


### 3 Dimensional Numpy Array
#### <font color ='red'>"Tensors (3-D or above)"</font>

In [28]:
c = np.array([[[1, 2, 3, 4],[5, 6, 7, 8]],[[9, 10, 11, 12],[13, 14, 15, 16]]])
print(c)
print("shape: {}".format(c.shape))
print("size: {}".format(c.size))
print("ndim: {}".format(c.ndim))
print("dtype: {}".format(c.dtype))
print("len(): {}".format(len(c)))

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
shape: (2, 2, 4)
size: 16
ndim: 3
dtype: int32
len(): 2


### Different Ways to Create ndarray
#### np.array(), np.zeros(), np.ones(),np.empty(),np.arange(start,stop,step),np.linspace(start,stop,number of points)

In [30]:
array_array = np.array([1, 2])
print(array_array)

[1 2]


In [34]:
zeros_array = np.zeros((2, 3),int)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


In [38]:
ones_array = np.ones((3,4),int)
print(ones_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [40]:
empty_array = np.empty((5,4))
print(empty_array)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 9.45743817e-308]
 [1.39071785e-307 7.56599807e-307 8.90104239e-307 1.24610383e-306]
 [1.69118108e-306 8.06632139e-308 1.20160711e-306 1.69119330e-306]
 [1.29062229e-306 1.24610383e-306 1.69118108e-306 8.90100844e-307]
 [1.60221072e-306 1.69120145e-306 1.11261909e-306 1.23712355e-311]]


In [48]:
arange_array = np.arange(10)
print(arange_array)

[0 1 2 3 4 5 6 7 8 9]


In [49]:
arange_array_1 = np.arange(0,10,2)
print(arange_array_1)

[0 2 4 6 8]


In [51]:
linspace_array = np.linspace(0,100,21)
print(linspace_array)

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]
