### 1 Dimensional Numpy Array
#### <font color='red'> "Vectors - 1D" </font>

In [5]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)
print("shape: {}".format(a.shape))
print("size: {}".format(a.size))
print("ndim: {}".format(a.ndim))
print("dtype: {}".format(a.dtype))
print("len(): {}".format(len(a)))

[ 1  2  3  4  5  6  7  8  9 10]
shape: (10,)
size: 10
ndim: 1
dtype: int32
len(): 10


### 2 Dimensional Numpy Array
#### <font color='red'> "Matrices - 2D" </font>

In [6]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[10, 11, 12]])
print(b)
print("shape: {}".format(b.shape))
print("size: {}".format(b.size))
print("ndim: {}".format(b.ndim))
print("dtype: {}".format(b.dtype))
print("len(): {}".format(len(b)))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
shape: (4, 3)
size: 12
ndim: 2
dtype: int32
len(): 4


### 3 Dimensional Numpy Array
#### <font color ='red'>"Tensors (3-D or above)"</font>

In [7]:
c = np.array([[[1, 2, 3, 4],[5, 6, 7, 8]],[[9, 10, 11, 12],[13, 14, 15, 16]]])
print(c)
print("shape: {}".format(c.shape))
print("size: {}".format(c.size))
print("ndim: {}".format(c.ndim))
print("dtype: {}".format(c.dtype))
print("len(): {}".format(len(c)))

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
shape: (2, 2, 4)
size: 16
ndim: 3
dtype: int32
len(): 2


### Different Ways to Create ndarray
#### np.array(), np.zeros(), np.ones(),np.empty(),np.arange(start,stop,step),np.linspace(start,stop,number of points)

In [8]:
array_array = np.array([1, 2])
print(array_array)

[1 2]


In [9]:
zeros_array = np.zeros((2, 3),int)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


In [10]:
ones_array = np.ones((3,4),int)
print(ones_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [11]:
empty_array = np.empty((5,4))
print(empty_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
arange_array = np.arange(10)
print(arange_array)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
arange_array_1 = np.arange(0,10,2)
print(arange_array_1)

[0 2 4 6 8]


In [14]:
linspace_array = np.linspace(0,100,21)
print(linspace_array)

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]


### Sorting an array with np.sort() function and ndarray.sort() method
np.sort() returns a sorted copy. ndarray.sort() sorts in place.

**numpy.sort(a, axis=-1, kind=None, order=None)
Return a sorted copy of an array.**

**Parameters:-**

a : array_like
Array to be sorted.

axis : int or None, optional
Axis along which to sort. If None, the array is flattened before sorting. The default is -1, which sorts along the last axis.

kind : {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}, optional
Sorting algorithm. The default is ‘quicksort’. Note that both ‘stable’ and ‘mergesort’ use timsort or radix sort under the covers and, in general, the actual implementation will vary with data type. The ‘mergesort’ option is retained for backwards compatibility.

Changed in version 1.15.0.: The ‘stable’ option was added.

order : str or list of str, optional
When a is an array with fields defined, this argument specifies which fields to compare first, second, etc. A single field can be specified as a string, and not all fields need be specified, but unspecified fields will still be used, in the order in which they come up in the dtype, to break ties.

**Returns:-**

sorted_array : ndarray
Array of the same type and shape as a.

In [45]:
## np.sort() function is different from inbuilt Python method sort(), it does not sort in-place. It returns a copy of the sorted array.
unsorted_array = np.random.randint(10,size=(10))
print("unsorted_array : {}".format(unsorted_array))
sorted_array= np.sort(unsorted_array,)
print("sorted_array : {}".format(sorted_array))
print("unsorted_array : {}".format(unsorted_array))

unsorted_array : [7 9 0 5 5 3 4 0 6 0]
sorted_array : [0 0 0 3 4 5 5 6 7 9]
unsorted_array : [7 9 0 5 5 3 4 0 6 0]


In [46]:
## np.sort() is different from inbuilt Python sort(), it does not sort in-place. It returns a copy of the sorted array.
unsorted_array_2D = np.random.randint(10,size=(3,5))
print("unsorted_array : ")
print(unsorted_array_2D)
sorted_array_2D= np.sort(unsorted_array_2D,axis=0)
print("sorted_array : ")
print(sorted_array_2D)
print("sorted_array flattened : ")
print(sorted_array_2D.reshape(15))
print("unsorted_array : ")
print(unsorted_array_2D)

unsorted_array : 
[[0 2 3 9 5]
 [3 7 0 0 8]
 [5 5 3 6 4]]
sorted_array : 
[[0 2 0 0 4]
 [3 5 3 6 5]
 [5 7 3 9 8]]
sorted_array flattened : 
[0 2 0 0 4 3 5 3 6 5 5 7 3 9 8]
unsorted_array : 
[[0 2 3 9 5]
 [3 7 0 0 8]
 [5 5 3 6 4]]


In [38]:
a = np.arange(30)
unsorted_array_3D = np.random.choice(a,size=(3,2,5),replace=False)
print("Unsorted Array 3D:-")
print(unsorted_array_3D)
sorted_array_3D = np.sort(unsorted_array_3D,axis=0)
print("Sorted Array 3D:-")
print(sorted_array_3D)

Unsorted Array 3D:-
[[[17 11  5  7  2]
  [27 22 12  6 20]]

 [[29 18 24 25 19]
  [10  4  3 15  8]]

 [[21  9 14  1 13]
  [28  0 23 26 16]]]
Sorted Array 3D:-
[[[17  9  5  1  2]
  [10  0  3  6  8]]

 [[21 11 14  7 13]
  [27  4 12 15 16]]

 [[29 18 24 25 19]
  [28 22 23 26 20]]]


### Understanding Axes and Dimensions from 4D onwards 

In [70]:
# Understanding 4 dimensions, sorting a 4D array on axis = 0.
# Anything after 3D is just repetition of 3 dimensions.
# 4D is a row of 3D cubes
# 5D is a sheet of 3D cubes
# 6D is a cube of 3D cubes
# 7D is a row of 6D cubes....
#set1 = np.arange(80)
#unsorted_array_4D = np.random.choice(set1,size=(2,2,4,5),replace=False)  
unsorted_array_4D = np.arange(80).reshape(2,2,4,5)
np.random.shuffle(unsorted_array_4D)
print("Unsorted Array")
print(unsorted_array_4D)
sorted_array_4D = np.sort(unsorted_array_4D,axis=0)
print("Sorted Array")
print(sorted_array_4D)


Unsorted Array
[[[[40 41 42 43 44]
   [45 46 47 48 49]
   [50 51 52 53 54]
   [55 56 57 58 59]]

  [[60 61 62 63 64]
   [65 66 67 68 69]
   [70 71 72 73 74]
   [75 76 77 78 79]]]


 [[[ 0  1  2  3  4]
   [ 5  6  7  8  9]
   [10 11 12 13 14]
   [15 16 17 18 19]]

  [[20 21 22 23 24]
   [25 26 27 28 29]
   [30 31 32 33 34]
   [35 36 37 38 39]]]]
Sorted Array
[[[[ 0  1  2  3  4]
   [ 5  6  7  8  9]
   [10 11 12 13 14]
   [15 16 17 18 19]]

  [[20 21 22 23 24]
   [25 26 27 28 29]
   [30 31 32 33 34]
   [35 36 37 38 39]]]


 [[[40 41 42 43 44]
   [45 46 47 48 49]
   [50 51 52 53 54]
   [55 56 57 58 59]]

  [[60 61 62 63 64]
   [65 66 67 68 69]
   [70 71 72 73 74]
   [75 76 77 78 79]]]]


### Concatenate()

In [79]:
a1 = np.arange(10).reshape(2,5)
a2 = np.arange(10,20).reshape(2,5)
a3 = np.arange(20,30).reshape(2,5)
a4 = np.concatenate((a1,a2,a3),axis=1)
print(a4)

[[ 0  1  2  3  4 10 11 12 13 14 20 21 22 23 24]
 [ 5  6  7  8  9 15 16 17 18 19 25 26 27 28 29]]


If you are ever interested in internal workings of NumPy arrays, please go to:-
https://numpy.org/doc/1.19/reference/internals.html#numpy-internals


In [81]:
a = np.array([1, 2, 3, 4, 5, 6])
row_vector = a[np.newaxis, :]
print(row_vector)
col_vector = a[:, np.newaxis]
print(col_vector)

[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


array([[0, 0, 1, 0],
       [0, 2, 4, 2]], dtype=int64)