**Indexing** is used to obtain individual elements from an array, but it can also be used to obtain entire rows, columns or planes from multi-dimensional arrays.

**Slicing** You can slice a numpy array is a similar way to slicing a list - except you can do it in more than one dimension.

As with indexing, the array you get back when you index or slice a numpy array is a view of the original array. It is the same data, just accessed in a different order. This is different to lists, where a slice returns a completely new list.

In [2]:
import numpy as np
arr_1D = np.random.randint(10,size=(5))
print(arr_1D)
print(arr_1D[4])

[5 3 0 5 2]
2


In [3]:
arr_2D = np.random.randint(10,size=(5,4))
print(arr_2D)
print("\n")
# Getting single element by indexing
print(arr_2D[3,2])
# Getting a column by slicing/indexing
print("\n")
print(arr_2D[:,2])
# Getting a row by slicing/indexing
print("\n")
print(arr_2D[2,:])

[[0 9 7 0]
 [2 2 7 4]
 [3 8 1 6]
 [1 9 5 8]
 [3 3 1 4]]


5


[7 7 1 5 1]


[3 8 1 6]


In [4]:
arr3D = np.random.randint(10,size=(2,3,4))
print(arr3D)

# Selecting a single component by indexing. Selecing 2nd plane, 1st row, 2nd column
print("\n")
print(arr3D[1,0,1])

[[[3 7 3 0]
  [6 6 4 2]
  [1 7 6 8]]

 [[7 8 6 7]
  [3 4 0 7]
  [7 2 4 2]]]


8


In [5]:
# Selecting a single row - First plane, 2nd row
print("\n")
print(arr3D[0,1,:])



[6 6 4 2]


In [6]:
# Selecting a single column - 2nd plane, 3rd column
print("\n")
print(arr3D[1,:,2])



[6 0 4]


In [7]:
# Selecing the middle horizontal plane
print("\n")
print(arr3D[:,1,:])



[[6 6 4 2]
 [3 4 0 7]]


In [8]:
# Selecting the third vertical plane
arr3D[:,:,2]

array([[3, 4, 6],
       [6, 0, 4]])

In [9]:
# Partial slice - 2nd vertical plane, middle and bottom row
arr3D[:,1:,1]

array([[6, 7],
       [4, 2]])

In [10]:
# Partial slice - 4th vertical plane, top row only
arr3D[:,0:1,3]

array([[0],
       [7]])

In [11]:
# Partial slice - 2nd vertical plane, 2nd column, 1st 2 rows only 
arr3D[1,0:2,1]

array([8, 4])

In [12]:
arr_2D

array([[0, 9, 7, 0],
       [2, 2, 7, 4],
       [3, 8, 1, 6],
       [1, 9, 5, 8],
       [3, 3, 1, 4]])

In [13]:
## Assignment of one array to another variable creates another view of the same array. They point to the same object.
arr_2D1 = arr_2D
print(id(arr_2D))
print(id(arr2_2D1))

2521917852528


NameError: name 'arr2_2D1' is not defined

In [ ]:
# Modification through the other variable reflects in the original array
arr_2D1[0,3] = 4
print(arr_2D)

In [ ]:
# Similarly, any slice of an array also is just a view of the same array. Any changes to the slice will reflect in the
# original array
arr_2D2 = arr_2D[1,:]
arr_2D2[2] = 3
arr_2D

### Boolean Indexing

It is a very common need to loop through an array and pick up elements that satisfy an if condition. This set of 'for' loop and 'if' statements are totally unnecessary for numpy arrays. As this entire process, of selecting elements from an array based on condition is handled by simply indexing the array itself with the condition, as simple as that. This awesome method is known as boolean indexing. Internally an array of booleans is passed as index.

In [ ]:
a1 = np.random.randint(10,size=(10))
print(a1)

In [ ]:
# Any relational operation or a combination of relational operations with the array variable yields an array of booleans
boolarr1 = a1>6
print(boolarr1)

In [ ]:
# The array of the booleans passed as index to original array will pick up only elements indedxed as True, elements indexed
# as False will be removed
a1[boolarr1]

In [ ]:
# Since both the relational expression and the resultant boolean array are equivalent. We can directly use the 
# relational expression on the array itself to index the array on basis of the condition. This is very useful
a1[a1>6]

In [ ]:
# Print Odd and Even numbers in the array in different arrays
print(a1[a1%2==0])
print(a1[a1%2!=0])

In [ ]:
# Complex conditions (Make sure you put each individual condition which are being and-ed/or-ed, in parentheses, or it
# does not work)
print(a1[(a1>2) & (a1<8)])
print(a1[(a1>2) | (a1<8)])

In [14]:
a2 = np.random.randint(20,size=(5,4))
a2


array([[ 8,  2,  8,  0],
       [12, 18,  0,  8],
       [ 1, 19,  8,  6],
       [17, 14, 19,  5],
       [ 0, 18, 15, 16]])

We can also use combinations of boolean indexing for some axis and normal integer indexing/slices for other axis
If we pass a one-dimensional array of booleans as an index to a 2D array, it will interpret the booleans to whether or not to select entire rows or entire columns.

In [15]:
a2_boolarr1 = (a2 % 2 == 0)
a2_boolarr1

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False,  True,  True],
       [False,  True, False, False],
       [ True,  True, False,  True]])

In [22]:
a2[a2_boolarr1]

array([ 8,  2,  8,  0, 12, 18,  0,  8,  8,  6, 14,  0, 18, 16])

In [23]:
a2_boolarr2 = [ True,  False,  True,  False , True]
a2_boolarr2

[True, False, True, False, True]

In [24]:
a2[a2_boolarr2,2]

array([ 8,  8, 15])

In [27]:
a2_boolarr3 = [True, True, False, False]
a2[:,a2_boolarr3]

array([[ 8,  2],
       [12, 18],
       [ 1, 19],
       [17, 14],
       [ 0, 18]])

### Fancy Indexing (Row/Column Numbers)

In [28]:
a2[[0,2,4]]

array([[ 8,  2,  8,  0],
       [ 1, 19,  8,  6],
       [ 0, 18, 15, 16]])

In [29]:
a2[:,[1,3]]

array([[ 2,  0],
       [18,  8],
       [19,  6],
       [14,  5],
       [18, 16]])

In [31]:
# a2[[0,2,4],[1,3]] --> This will fail. Intuitively it appears as if we are looking for the intersection 
# of these rows/columns by saying above, but actually it creates a corresponding 2-tuple from both lists. 
# So instead below will give us exactly 3 elements-  a2[0,0],a2[2,1],a2[4,3]
a2[[0,2,4],[0,1,3]]

array([ 8, 19, 16])

In [38]:
#In order to do what we actually wanted to do, we can first use fancy indexing for rows and then again on top of that
# indexed array, again use fancy indexing for columns
a2[[0,2,4]][:,[1,3]]

array([[ 2,  0],
       [19,  6],
       [18, 16]])