In [1]:
import numpy as np

In [3]:
# Problem 1
list1 = list(map(int, input().split()))
arr1 = np.array(list1)
print(arr1.reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Problem 2
N,M = tuple(map(int,input().split()))
list2 = []

for _ in range(N):
    row_i = list(map(int,input().split()))
    list2.append(row_i)

arr2 = np.array(list2)
print(np.transpose(arr2))
print(arr2.flatten())


In [17]:
# Problem 3 Pre-requisite, Seems concatenate(axis 0) is same as vstack,
# and concatenate(axis=1) is same as hstack
array_1 = np.array([[1,2,3],[0,0,0]])
array_2 = np.array([[0,0,0],[7,8,9]])
print(np.concatenate((array_1, array_2)))  
print(np.concatenate((array_1, array_2),axis=1))
print(np.hstack((array_1,array_2)))
print(np.vstack((array_1,array_2)))

[[1 2 3]
 [0 0 0]
 [0 0 0]
 [7 8 9]]
[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]
[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]
[[1 2 3]
 [0 0 0]
 [0 0 0]
 [7 8 9]]


In [25]:
# Problem 3
N,M,P = tuple(map(int,input().split()))
list_p3_1 = []
for i in range(N):
    list_p3_1.append(list(map(int,input().split())))
    
list_p3_2 = []
for i in range(M):
    list_p3_2.append(list(map(int,input().split())))

array_p3_1 = np.array(list_p3_1)
print(array_p3_1)
array_p3_2 = np.array(list_p3_2)
print(array_p3_2)

print(np.concatenate((array_p3_1,array_p3_2),axis=0))
    
        

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]]
[[3 4]
 [3 4]
 [3 4]]
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [30]:
# Problem 3, Alternative solution using list comprehensions to shorten the code and remove
# for loops
N, M, P = map(int, input().split())
n = np.array([list(map(int, input().split())) for _ in range(N)])
m = np.array([list(map(int, input().split())) for _ in range(M)])
print(np.concatenate((n, m)))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [31]:
tp4 = tuple(map(int,input().split()))
print(np.zeros(tp4, dtype=int))
print(np.ones(tp4,dtype=int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [32]:
# Problem 5, usage of replace is funny here, its just to match the answer set by the problem
# setter(he incorrectly has added whitespaces to each array element). In the actual solution
# replace can be omitted
N,M = tuple(map(int,input().split()))
print(str(np.eye(N,M,k=0)).replace('1',' 1').replace('0',' 0'))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
# Problem 6, Array Mathematics
N,M = map(int,input().split())
A = np.array([list(map(int,input().split())) for _ in range(N)])
B = np.array([list(map(int,input().split())) for _ in range(N)])
print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [42]:
# Problem 7, floor,ceil,rint. If answer does not match due to whitespacing use
# np.set_printoptions(sign=' ')
A = np.array(list(map(float,input().split())))
print(np.floor(A))
print(np.ceil(A))
print(np.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [43]:
# Problem 8, sum, prod
N,M = map(int,input().split())
arrp8 = np.array([list(map(int,input().split())) for _ in range(N)])
arrp8_sum = np.sum(arrp8,axis=0)
arrp8_sum_prod = np.prod(arrp8_sum)
print(arrp8_sum_prod)

2 2
1 2
3 4
24


In [46]:
# Problem 9, min, max
N,M = map(int,input().split())
arrp9 = np.array([list(map(int,input().split())) for _ in range(N)])
print(np.max(np.min(arrp9,axis=1)))

4 2
2 5
3 7
1 3
4 0
3


In [59]:
# Problem 10 mean, var, std :: Some code is added to match the incorrect answer set by problem
# setter - rounding and np.set_printoptions(sign=' ')
N,M = map(int,input().split())
arrp10 = np.array([list(map(int,input().split())) for _ in range(N)])
print(np.mean(arrp10,axis=1))
print(np.var(arrp10,axis=0))
x = np.float32(np.std(arrp10,axis=None))
print(round(np.std(arrp10,axis=None),11))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.11803398875


In [54]:
#Problem 10. Below code statisfies the print properties. Learnt a new trick to set printoptions
# resolves both the rounding need and the spacing need of older numpy printing
# Commented that out below so that it does not apply to this notebook

#np.set_printoptions(legacy='1.13')
N,M = map(int,input().split())
arrp10 = np.array([list(map(int,input().split())) for _ in range(N)])
print(np.mean(arrp10,axis=1))
print(np.var(arrp10,axis=0))
print(np.std(arrp10,axis=None))

1.11803398875

In [60]:
# Problem 11.
N = int(input())
A = np.array([list(map(int,input().split())) for _ in range(N)])
B = np.array([list(map(int,input().split())) for _ in range(N)])
print(np.dot(A,B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [61]:
# Problem 12, np.linalg, Finding determinant of a matrix
N = int(input())
arrp12 = np.array([list(map(float,input().split())) for _ in range(N)])
print(np.linalg.det(arrp12))

2
1.1 1.1
1.1 1.1
0.0
