### Simple random data:-
- randint
- rand
- randn
- choice

### Permutation:-
- shuffle
- permutation

#### What is a Random Number?
Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

Pseudo Random and True Random.
Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless its related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).*

#### Numpy documentation for random, both old and new conventions
https://numpy.org/doc/stable/reference/random/legacy.html

https://numpy.org/doc/stable/reference/random/generator.html
#### Good tutorial for Numpy with examples from random
https://www.w3schools.com/python/numpy_random.asp

### LEGACY RandomState functions

### **np.random.randint()**

In [2]:
import numpy as np

# Random integer within low to high inclusive, using np.random.randint(low[high,size,dtype])
for _ in range(10):
    x1 = np.random.randint(-5,5)
    print(x1)

4
-5
-5
-2
-2
-2
-1
1
-2
2


In [3]:
# Creating n-D arrays of integers using np.random.randint(low[high,size,dtype])
for _ in range(3):
    random_int1D_array = np.random.randint(100, size = (5))
    print(random_int1D_array)
    print('\n')
for _ in range(3):
    random_int2D_array = np.random.randint(100, size = (3,4))
    print(random_int2D_array)
    print('\n')

[35 31 39  1 54]


[65 15 10 39 35]


[58 42 74 13 70]


[[86 60 15 20]
 [11 46 46 77]
 [89  3  0 70]]


[[29 33 34 53]
 [ 6  1 41  2]
 [24 38 47  9]]


[[96 59 41  8]
 [83 29 16 30]
 [ 1 10  3 49]]




### **np.random.rand()**

In [4]:
# np.random.rand([d0,d1,...,dn]), if no parameters, will generate a single float in the half open interval,
# if d0,d1,..,dn specified, it will generate an ndarray of such floats with shape(d0,d1,..,dn).

In [5]:
for _ in range(10):
    x3 = np.random.rand()
    print(x3)

0.3618251061938529
0.847575247087761
0.6132556752693856
0.4661183016387126
0.6498251481588596
0.5054859121973986
0.10998215223600194
0.04524308894777129
0.11370690754021406
0.12782926095105718


In [6]:
for _ in range(3):
    x4 = np.random.rand(5,6)
    print(x4)
    print('\n')

[[0.77907671 0.90445912 0.09008742 0.09901104 0.88270017 0.78520305]
 [0.07753717 0.75506546 0.88987363 0.64835353 0.6405518  0.56241611]
 [0.26831116 0.69126848 0.48455121 0.89179768 0.62667485 0.08132992]
 [0.11833989 0.74650456 0.08802225 0.08724793 0.02224356 0.96231949]
 [0.73529885 0.54773147 0.61650941 0.73525701 0.42262706 0.26408277]]


[[0.55200434 0.39680648 0.70720393 0.75732767 0.24354948 0.11661901]
 [0.50280748 0.57408839 0.45025908 0.93234964 0.47348952 0.10453528]
 [0.91902234 0.46067467 0.9647214  0.0913211  0.95611141 0.35498425]
 [0.85864395 0.39464506 0.83763437 0.86964077 0.47870798 0.43996208]
 [0.56416194 0.04190104 0.00500986 0.93895342 0.63849967 0.79163531]]


[[0.6018863  0.99947489 0.43333446 0.21750948 0.73319094 0.46071633]
 [0.97031009 0.53108896 0.75779614 0.31969667 0.34626341 0.25689743]
 [0.03708024 0.67412739 0.0087407  0.48417377 0.85490657 0.67440589]
 [0.72010058 0.92262747 0.27839445 0.51416353 0.48304742 0.53755446]
 [0.06558711 0.93877708 0.79

### **np.random.randn()** 

In [7]:
for _ in range(10):
    a_random_standard_normal_value = np.random.randn()
    print(a_random_standard_normal_value)

0.3240741069137989
0.3517179206340476
-0.2155211510564386
2.036105405442813
-0.44479872820527666
-0.7178718332366965
0.9556510975936305
-0.7474721733272308
-0.8584807740290811
-0.010128259580902715


In [8]:
for _ in range(3):
    arrayof_standard_normal_values = np.random.randn(3,4)
    print(arrayof_standard_normal_values)
    print('\n')

[[ 0.31287812 -0.21361704  0.54803775  0.3837286 ]
 [ 0.89162208  0.18169285  2.05339853 -1.50057993]
 [-0.05387982 -0.36828005  1.93057585  0.09255162]]


[[-0.44069435  0.62152566  0.40073996  0.18340976]
 [-1.45380511  1.08922358 -0.60147016  0.67553533]
 [ 0.54017882  0.05607328 -0.92814972 -2.13360032]]


[[ 0.13399889 -0.34835812 -0.09576704 -0.4610192 ]
 [ 0.54208756  0.71815902  1.66880398  2.55916536]
 [ 1.69574168  0.48811458  0.14238109 -0.82027395]]




### **np.random.choice()** 

In [9]:
# np.random.choice(a, size=None, replace=True, p=None)¶
# Takes a 1-D ndarray. Generates a random sample (single or as per shape) from that, with or without replacement 
# (default=with), can optionally give 1-D ndarray of separte probabilities for our set of possible values.

In [10]:
possible_values = np.arange(10,101,10)
#probability = np.array([0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1])
probability = np.array([0.0,0.0,0.0,0.8,0.2,0.0,0.0,0.0,0.0,0.0])

print("Single Random Choice:-")
for _ in range(3):
    single_random_choice = np.random.choice(possible_values)
    print(single_random_choice)

#This one demonstrates how a keyword parameter has to be mentioned, which comes in the way of another keyword parameter
print("Single Random Choice with bias in probabilty:-")
for _ in range(3):
    single_random_choice = np.random.choice(possible_values,size=None,replace=True,p=probability)
    print(single_random_choice)
    
print("Array Random Choice:-")
for _ in range(3):   
    array_random_choice = np.random.choice(possible_values,(5,8))
    print(array_random_choice)
    print('\n')
print("Array Random Choice without replacement:-")
# For without replacement, care needs to be taken, that output array size should not exceed the number of possible values
for _ in range(2):   
    array_random_choice_without_replacement = np.random.choice(possible_values,(2,5),replace=False)
    print(array_random_choice_without_replacement)
    print('\n')
print("Array Random Choice with probability:-")
for _ in range(2):   
    array_random_choice_with_probability = np.random.choice(possible_values,(5,8),replace=True,p=probability)
    print(array_random_choice_with_probability)
    print('\n')

Single Random Choice:-
20
20
40
Single Random Choice with bias in probabilty:-
40
50
40
Array Random Choice:-
[[ 70  80  30  20  40  60  70  10]
 [100  40  40  80  30  60  70  60]
 [ 70  90  50  70  20  70  90  10]
 [ 60  80  70  50  50  20 100  20]
 [ 60  40 100  30  70  30  10  60]]


[[ 30  60 100  20  60  80  40  50]
 [ 70  20  90  80  60  10  20  80]
 [ 10  40 100  60  10  60  20  80]
 [100  80 100  90  60  40  10  30]
 [ 80  80  80  10  60  10  30  50]]


[[ 30  30  60  50  40  70  70  10]
 [ 90  90  40  90  70 100  50  70]
 [ 90  90  90  80  10  10  90  90]
 [ 30  30 100  40  80  30  50  80]
 [ 80  50  50  40  70  30  30  90]]


Array Random Choice without replacement:-
[[ 90  10  20  30 100]
 [ 60  40  70  80  50]]


[[ 70  10  50  20  30]
 [ 90  40 100  60  80]]


Array Random Choice with probability:-
[[40 40 40 40 50 40 40 40]
 [50 40 50 40 40 40 50 40]
 [40 40 40 40 40 40 40 40]
 [50 50 40 40 40 40 40 50]
 [40 40 40 40 40 40 40 50]]


[[50 40 40 40 50 50 40 50]
 [40 40 40 4

In [11]:
# choice function works with non-numeric data as well, since the list of possible values is taken as input from user 
char_array = np.array(['A1','A2','A3','B1','B2','B3','C1','C2','C3'])
choice_array = np.random.choice(char_array,(3,3))
print(choice_array)

[['B3' 'A2' 'C1']
 ['C3' 'B3' 'C3']
 ['B2' 'C1' 'B3']]


Key inference is: When x is an array, both numpy.random.permutation(x) and numpy.random.shuffle(x) can permute the elements in x randomly along the first axis. numpy.random.permutation(x) actually returns a new variable and the original data is not changed. Where as numpy.random.shuffle(x) has changed original data and does not return a new variable.
Also, permutation can take an int as a parameter and treats it as np.arange(x). Shuffle only takes array_like(array or list) as parameter.

### **np.random.shuffle()** 
np.random.shuffle(x)

Parameters:-
x - array_like (The array or list to be shuffled)

Returns:-
None

### **np.random.permutation()** 
Parameters:-
xint or array_like
If x is an integer, randomly permute np.arange(x). If x is an array, make a copy and shuffle the elements randomly.

Returns:-
ndarray (Permuted sequence or array range)

#### Difference between shuffle() and permuation()
- When x is an array, both numpy.random.permutation(x) and numpy.random.shuffle(x) can permute the elements in x randomly along the first axis. numpy.random.permutation(x) actually returns a new variable and the original data is not changed. Where as numpy.random.shuffle(x) has changed original data and does not return a new variable.
- Also, permutation can take an int as a parameter and treats it as np.arange(x). Shuffle only takes array_like(array or list) as parameter.

In [12]:
base_array_shuffle = np.arange(10)
print("Shuffling happens in place:-")
for _ in range(3):
    np.random.shuffle(base_array_shuffle)
    print ("Base Array: {}".format(base_array_shuffle))
    print('\n')

print("Permutation returns a copy of the permuted array:-")

base_array_permute = np.arange(10)
for _ in range(3):
    permute_array = np.random.permutation(base_array_permute)
    print ("Permuted Array: {}".format(permute_array))
    print ("Base Array: {}".format(base_array_permute))
#    print(permute_array)
    print('\n')

Shuffling happens in place:-
Base Array: [4 0 9 3 2 8 7 1 5 6]


Base Array: [4 7 2 6 0 5 8 9 3 1]


Base Array: [0 5 8 7 4 9 2 3 1 6]


Permutation returns a copy of the permuted array:-
Permuted Array: [0 8 2 7 4 3 5 6 9 1]
Base Array: [0 1 2 3 4 5 6 7 8 9]


Permuted Array: [7 0 1 3 4 2 8 5 9 6]
Base Array: [0 1 2 3 4 5 6 7 8 9]


Permuted Array: [0 5 4 3 6 1 9 8 7 2]
Base Array: [0 1 2 3 4 5 6 7 8 9]




In [13]:
base_array_1= np.arange(36).reshape(4,3,3)
print("Base Array Shuffle:")
print(base_array_1)
print("Shuffling happens only along the first axis:-")
np.random.shuffle(base_array_1)
print("Base Array After shuffle: ")
print(base_array_1)

base_array_2= np.arange(36).reshape(4,3,3)
print("Base Array Permutation: ")
print(base_array_2)
print("Permutation also happens only along the first axis:-")
permute_array_2 = np.random.permutation(base_array_2)
print("Permuted Array : ")
print(permute_array_2)



Base Array Shuffle:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]]
Shuffling happens only along the first axis:-
Base Array After shuffle: 
[[[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
Base Array Permutation: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]]
Permutation also happens only along the first axis:-
Permuted Array : 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


### GENERATOR functions and usage

In [14]:
rng = np.random.default_rng()
rng.integers(5, size=(2, 4))

array([[0, 4, 1, 0],
       [4, 4, 3, 0]], dtype=int64)