In [3]:
import numpy as np

In [8]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## *---Unary ufunc---*    
Universal NumPy functions that take arrays as arguments and do Vectorized operation on all elements

In [7]:
np.sqrt(a1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [9]:
np.exp(a1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [10]:
a2 = np.random.randn(3,4)
a2

array([[-1.06142275, -0.88635396,  1.46924069, -0.05009354],
       [ 0.41832765,  0.27222222, -0.78199484,  1.90204076],
       [ 0.44066872,  0.00771258,  1.7115812 ,  0.41842482]])

In [11]:
np.abs(a2)

array([[1.06142275, 0.88635396, 1.46924069, 0.05009354],
       [0.41832765, 0.27222222, 0.78199484, 1.90204076],
       [0.44066872, 0.00771258, 1.7115812 , 0.41842482]])

In [13]:
np.sign(a2)

array([[-1., -1.,  1., -1.],
       [ 1.,  1., -1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [14]:
np.ceil(a2)

array([[-1., -0.,  2., -0.],
       [ 1.,  1., -0.,  2.],
       [ 1.,  1.,  2.,  1.]])

In [16]:
np.floor(a2)

array([[-2., -1.,  1., -1.],
       [ 0.,  0., -1.,  1.],
       [ 0.,  0.,  1.,  0.]])

In [18]:
np.rint(a2)

array([[-1., -1.,  1., -0.],
       [ 0.,  0., -1.,  2.],
       [ 0.,  0.,  2.,  0.]])

In [20]:
np.modf(a2)

(array([[-0.06142275, -0.88635396,  0.46924069, -0.05009354],
        [ 0.41832765,  0.27222222, -0.78199484,  0.90204076],
        [ 0.44066872,  0.00771258,  0.7115812 ,  0.41842482]]),
 array([[-1., -0.,  1., -0.],
        [ 0.,  0., -0.,  1.],
        [ 0.,  0.,  1.,  0.]]))

In [22]:
np.isnan(a2)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [23]:
np.logical_not(a2)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

## *---Binary ufunc---*    

In [33]:
a3 = np.arange(8).reshape(2,4)
a4 = np.arange(8).reshape(2,4)
print(np.add(a3,a4))
print(np.subtract(a3,a4))
print(np.multiply(a3,a4))

[[ 0  2  4  6]
 [ 8 10 12 14]]
[[0 0 0 0]
 [0 0 0 0]]
[[ 0  1  4  9]
 [16 25 36 49]]


In [39]:
a5 = np.random.rand(10)
print(a5)
print("\n")
a6 = np.ones(10)
print(a6)
print("\n")
a7 = np.floor_divide(a5,a6)
print(a7)
print(np.floor_divide(5,2))

[0.39770769 0.92595645 0.68631548 0.27679966 0.19290418 0.45510085
 0.44031629 0.78525075 0.2955882  0.34864224]


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2
