#### What is a Random Number?
Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

Pseudo Random and True Random.
Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless its related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).*

#### Numpy documentation for random, both old and new conventions
https://numpy.org/doc/stable/reference/random/legacy.html

https://numpy.org/doc/stable/reference/random/generator.html
#### Good tutorial for Numpy with examples from random
https://www.w3schools.com/python/numpy_random.asp

### LEGACY RandomState functions

### <font color='red'> **randint()** </font> 

In [29]:
import numpy as np

# Random integer within low to high inclusive, using np.random.randint(low[high,size,dtype])
for _ in range(10):
    x1 = np.random.randint(95,100)
    print(x1)

96
96
98
99
99
96
96
97
96
96


In [26]:
# Creating n-D arrays of integers using np.random.randint(low[high,size,dtype])
for _ in range(3):
    random_int1D_array = np.random.randint(100, size = (5))
    print(random_int1D_array)
    print('\n')
for _ in range(3):
    random_int2D_array = np.random.randint(100, size = (3,4))
    print(random_int2D_array)
    print('\n')

[95 64 93 31 13]


[88 82 48 70 91]


[38 84 16 33 40]


[[ 7 45 19 90]
 [64 81 44 85]
 [ 9 14 45 51]]


[[25 86 35 69]
 [56 30 83 75]
 [54 23 67  5]]


[[64 90 23 55]
 [36 90 96 29]
 [89  6 93 54]]




### <font color='red'> **rand()** </font> 

In [ ]:
# np.random.rand([d0,d1,...,dn]), if no parameters, will generate a single float in the half open interval,
# if d0,d1,..,dn specified, it will generate an ndarray of such floats with shape(d0,d1,..,dn).

In [22]:
for _ in range(10):
    x3 = np.random.rand()
    print(x3)

0.3488058782111365
0.37911430250263556
0.6367077547938438
0.9061411037215459
0.18852474955738285
0.732427118030772
0.9078863838588698
0.2166426802955107
0.9075284125832975
0.2535900754293492


In [32]:
for _ in range(3):
    x4 = np.random.rand(5,6)
    print(x4)
    print('\n')

[[0.03638702 0.08121715 0.82820379 0.27093234 0.80700921 0.72322683]
 [0.69464488 0.82902349 0.02633425 0.40456162 0.21088666 0.82469934]
 [0.92298383 0.66822082 0.34784552 0.59860484 0.02973187 0.16421656]
 [0.53084648 0.95938207 0.83521029 0.27729013 0.41855912 0.0677496 ]
 [0.33285358 0.76298904 0.96835406 0.01688075 0.39521113 0.40687285]]


[[0.86540151 0.15774289 0.12499859 0.23733526 0.69507807 0.48776115]
 [0.60693825 0.50365951 0.96239135 0.61643002 0.38665852 0.4925935 ]
 [0.78551036 0.03333771 0.95456843 0.79204872 0.10432664 0.96985669]
 [0.510031   0.84106314 0.05360815 0.80951438 0.49626096 0.9967051 ]
 [0.45677708 0.76805546 0.18286251 0.17239647 0.13646436 0.69860868]]


[[0.33729466 0.88641975 0.19027243 0.14949044 0.20634675 0.22341712]
 [0.11522582 0.91778502 0.66748862 0.75953743 0.33729435 0.54416247]
 [0.0775967  0.95600865 0.05230388 0.72317477 0.85051987 0.62670991]
 [0.03691442 0.07373991 0.75401792 0.77866625 0.45448926 0.86746504]
 [0.44563963 0.83322695 0.32

### <font color='red'> **randn()** </font> 

In [33]:
for _ in range(10):
    a_random_standard_normal_value = np.random.randn()
    print(a_random_standard_normal_value)

-0.38258358246421625
-1.52021896019382
-0.09802980738084827
0.021520920569859447
-0.4480519289926931
-0.741350608418689
0.18787076089074992
0.4663701566941468
1.4508751675944118
-0.817372794983149


In [37]:
for _ in range(3):
    arrayof_standard_normal_values = np.random.randn(3,4)
    print(arrayof_standard_normal_values)
    print('\n')

[[ 1.024892   -0.05368681  0.37010922  0.5166434 ]
 [ 1.06792172  0.31379867 -0.63915898 -0.99608196]
 [-0.76680886 -1.65154156 -1.26481783 -0.5429189 ]]


[[-0.94477457  0.3780253  -1.41585324 -0.15312357]
 [ 0.78532881  0.38297465 -2.53056678  0.60512365]
 [-1.35376082 -1.32043643 -1.12397922  0.59054506]]


[[-0.63344261 -1.99415012  0.94144922  0.20580952]
 [-0.82482635 -1.16062559  0.11667148  0.52113236]
 [-1.66509162 -1.48123432 -1.60066084 -0.69633386]]




### <font color='red'> **choice()** </font> 

In [ ]:
# np.random.choice(a, size=None, replace=True, p=None)¶
# Takes a 1-D ndarray. Generates a random sample (single or as per shape) from that, with or without replacement 
# (default=with), can optionally give 1-D ndarray of separte probabilities for our set of possible values.

In [48]:
possible_values = np.arange(10,101,10)
#probability = np.array([0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1])
probability = np.array([0.0,0.0,0.0,0.8,0.2,0.0,0.0,0.0,0.0,0.0])

print("Single Random Choice:-")
for _ in range(3):
    single_random_choice = np.random.choice(possible_values)
    print(single_random_choice)
print("Array Random Choice:-")
for _ in range(3):   
    array_random_choice = np.random.choice(possible_values,(5,8))
    print(array_random_choice)
    print('\n')
print("Array Random Choice without replacement:-")
# For without replacement, care needs to be taken, that output array size should not exceed the number of possible values
for _ in range(2):   
    array_random_choice_without_replacement = np.random.choice(possible_values,(2,5),replace=False)
    print(array_random_choice_without_replacement)
    print('\n')
print("Array Random Choice with probability:-")
for _ in range(2):   
    array_random_choice_with_probability = np.random.choice(possible_values,(5,8),replace=True,p=probability)
    print(array_random_choice_with_probability)
    print('\n')

Single Random Choice:-
30
10
20
Array Random Choice:-
[[ 30  70  90  40  10  80 100  60]
 [ 70  40  20  90  10  70  20  50]
 [ 80  30  70  60  70  20  70  60]
 [ 50  40  50  50  60  80  90  40]
 [ 50  40 100  70 100  90  70 100]]


[[ 20  90 100  10  50  90 100  80]
 [ 50  80  80  60  70  90  10  50]
 [ 50  90  20  90  80  10  20  90]
 [ 10  40  70  20  10  20  90  90]
 [ 70 100  10  50  80  40  90  70]]


[[ 40  50  50  50  90  80  50  60]
 [ 70  30  30  30  70 100  60  20]
 [ 60  70  30  50  40  20  40  30]
 [ 70  80  60  10  90  80 100  90]
 [ 10  90  60  90  20 100  20  70]]


Array Random Choice without replacement:-
[[ 50  20  40  70  10]
 [100  60  30  90  80]]


[[ 30  80  10  90  50]
 [ 60 100  40  70  20]]


Array Random Choice with probability:-
[[50 40 40 40 40 40 50 50]
 [50 40 40 40 40 50 40 40]
 [40 50 50 50 40 40 50 40]
 [40 50 50 50 40 40 40 50]
 [40 40 40 40 40 40 40 40]]


[[50 40 40 40 50 40 40 40]
 [40 40 40 40 40 40 40 40]
 [50 50 40 40 40 40 40 50]
 [40 50 40 40 

Key inference is: When x is an array, both numpy.random.permutation(x) and numpy.random.shuffle(x) can permute the elements in x randomly along the first axis. numpy.random.permutation(x) actually returns a new variable and the original data is not changed. Where as numpy.random.shuffle(x) has changed original data and does not return a new variable.

### <font color='red'> **shuffle()** </font> 

### <font color='red'> **permutation()** </font> 

### GENERATOR functions and usage