### Simple random data:-
- randint
- rand
- randn
- choice

### Permutation:-
- shuffle
- permutation

#### What is a Random Number?
Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

Pseudo Random and True Random.
Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless its related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).*

#### Numpy documentation for random, both old and new conventions
https://numpy.org/doc/stable/reference/random/legacy.html

https://numpy.org/doc/stable/reference/random/generator.html
#### Good tutorial for Numpy with examples from random
https://www.w3schools.com/python/numpy_random.asp

### LEGACY RandomState functions

### **np.random.randint()**

In [72]:
import numpy as np

# Random integer within low to high inclusive, using np.random.randint(low[high,size,dtype])
for _ in range(10):
    x1 = np.random.randint(-5,5)
    print(x1)

-2
-4
-1
-4
-1
-5
1
-2
4
-5


In [50]:
# Creating n-D arrays of integers using np.random.randint(low[high,size,dtype])
for _ in range(3):
    random_int1D_array = np.random.randint(100, size = (5))
    print(random_int1D_array)
    print('\n')
for _ in range(3):
    random_int2D_array = np.random.randint(100, size = (3,4))
    print(random_int2D_array)
    print('\n')

[19 99 63 40 33]


[ 3 85 37 28 28]


[92 64 55 58 34]


[[28 34 46 30]
 [13 54 86 38]
 [76 19 61 91]]


[[64 20 34 25]
 [73 17  8 43]
 [11 31 62 85]]


[[88 42 74 31]
 [52 91 25 64]
 [ 4 16 69 54]]




### **np.random.rand()**

In [51]:
# np.random.rand([d0,d1,...,dn]), if no parameters, will generate a single float in the half open interval,
# if d0,d1,..,dn specified, it will generate an ndarray of such floats with shape(d0,d1,..,dn).

In [52]:
for _ in range(10):
    x3 = np.random.rand()
    print(x3)

0.2042690733910294
0.19171996677144865
0.5468848020688242
0.9435535743623906
0.5362678292149539
0.6393898047436216
0.8403758927500689
0.5043999180380021
0.8963577976698461
0.5948255481621151


In [53]:
for _ in range(3):
    x4 = np.random.rand(5,6)
    print(x4)
    print('\n')

[[0.11669046 0.27807312 0.89560653 0.88792637 0.630661   0.68285442]
 [0.36556084 0.64386753 0.19683801 0.98657446 0.6883504  0.46254804]
 [0.5971681  0.26039916 0.13110501 0.80110604 0.87028308 0.95875101]
 [0.02570375 0.49268248 0.84256139 0.81000367 0.64496504 0.50873716]
 [0.17899204 0.24025837 0.49668854 0.46390654 0.30342406 0.71783971]]


[[0.88433741 0.60137395 0.52467752 0.40550279 0.43930413 0.38656008]
 [0.44146701 0.94276315 0.40768607 0.35463408 0.61623444 0.33187361]
 [0.26929356 0.93047269 0.76888178 0.73235713 0.87471064 0.34901799]
 [0.62555337 0.51118177 0.4803325  0.37832825 0.88532368 0.57703499]
 [0.06361989 0.81944679 0.55900598 0.78389665 0.05794224 0.36065775]]


[[0.20370128 0.96882354 0.46010798 0.13956295 0.28977841 0.39142578]
 [0.55441519 0.85558669 0.36795048 0.16177254 0.88168013 0.82752531]
 [0.27930216 0.55225036 0.50946817 0.85562584 0.22106758 0.72093801]
 [0.11793384 0.88671257 0.5452486  0.98907213 0.67425469 0.40904566]
 [0.81607011 0.71590042 0.42

### **np.random.randn()** 

In [54]:
for _ in range(10):
    a_random_standard_normal_value = np.random.randn()
    print(a_random_standard_normal_value)

-0.7674759100524069
-0.8257202697333841
1.373476760451037
-0.03226311150757659
-0.5638355075983118
-0.7398815186556331
-0.3829204552216758
0.8273699279973378
0.8235869040318119
-0.13343508171625668


In [55]:
for _ in range(3):
    arrayof_standard_normal_values = np.random.randn(3,4)
    print(arrayof_standard_normal_values)
    print('\n')

[[-2.30309631 -0.40671201  1.10512902  0.34247142]
 [ 0.14230089 -0.9059688   0.12276971  0.03366308]
 [ 1.15115437  0.71069772  0.98744273 -0.20217924]]


[[ 0.23990217 -0.31213345  1.76340122 -2.40216314]
 [-1.85363661 -0.80584375 -0.9006484  -0.59364415]
 [-2.38069535 -0.01797681 -1.20100575 -1.03649297]]


[[ 0.95767828  0.27052346  0.49963807  0.05488375]
 [-0.02097469  0.21959607  0.61696486  0.22194785]
 [-0.78299867 -3.05110132  1.24381545  1.99001936]]




### **np.random.choice()** 

In [56]:
# np.random.choice(a, size=None, replace=True, p=None)¶
# Takes a 1-D ndarray. Generates a random sample (single or as per shape) from that, with or without replacement 
# (default=with), can optionally give 1-D ndarray of separte probabilities for our set of possible values.

In [57]:
possible_values = np.arange(10,101,10)
#probability = np.array([0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1])
probability = np.array([0.0,0.0,0.0,0.8,0.2,0.0,0.0,0.0,0.0,0.0])

print("Single Random Choice:-")
for _ in range(3):
    single_random_choice = np.random.choice(possible_values)
    print(single_random_choice)
print("Array Random Choice:-")
for _ in range(3):   
    array_random_choice = np.random.choice(possible_values,(5,8))
    print(array_random_choice)
    print('\n')
print("Array Random Choice without replacement:-")
# For without replacement, care needs to be taken, that output array size should not exceed the number of possible values
for _ in range(2):   
    array_random_choice_without_replacement = np.random.choice(possible_values,(2,5),replace=False)
    print(array_random_choice_without_replacement)
    print('\n')
print("Array Random Choice with probability:-")
for _ in range(2):   
    array_random_choice_with_probability = np.random.choice(possible_values,(5,8),replace=True,p=probability)
    print(array_random_choice_with_probability)
    print('\n')

Single Random Choice:-
100
30
70
Array Random Choice:-
[[ 20  50  30  70  60 100  90  20]
 [ 70  50  40  80  20  60  80  60]
 [100  40  80 100 100  40  70  40]
 [ 40 100  40 100  80  80  60  70]
 [ 80 100  20  40  20  30 100  40]]


[[ 30 100 100  50  80  80 100 100]
 [100  70  60  80  60  20  20  90]
 [ 30  60  70  20  80  80  40  40]
 [ 40  50  80  30  40  10  20  50]
 [ 70  30  30  60  80  10  80  70]]


[[ 80  10  30  90  80  70  90  50]
 [ 90  90  50  40  10  60  20  80]
 [ 10  60  80  40  20  20  50 100]
 [ 90  80  60  70  50  90  40  70]
 [ 90  70  10  50 100  40  10  10]]


Array Random Choice without replacement:-
[[100  10  60  20  80]
 [ 50  90  40  30  70]]


[[100  80  20  70  50]
 [ 90  60  30  10  40]]


Array Random Choice with probability:-
[[40 40 40 40 40 40 40 40]
 [40 40 40 50 40 40 40 50]
 [40 40 40 40 40 40 40 40]
 [40 40 40 40 40 40 40 40]
 [40 50 40 40 50 40 40 50]]


[[40 40 40 40 40 50 40 40]
 [50 50 40 40 40 50 40 50]
 [40 40 40 40 40 40 40 40]
 [50 40 40 40

Key inference is: When x is an array, both numpy.random.permutation(x) and numpy.random.shuffle(x) can permute the elements in x randomly along the first axis. numpy.random.permutation(x) actually returns a new variable and the original data is not changed. Where as numpy.random.shuffle(x) has changed original data and does not return a new variable.
Also, permutation can take an int as a parameter and treats it as np.arange(x). Shuffle only takes array_like(array or list) as parameter.

### **np.random.shuffle()** 
np.random.shuffle(x)

Parameters:-
x - array_like (The array or list to be shuffled)

Returns:-
None

### **np.random.permutation()** 
Parameters:-
xint or array_like
If x is an integer, randomly permute np.arange(x). If x is an array, make a copy and shuffle the elements randomly.

Returns:-
ndarray (Permuted sequence or array range)

#### Difference between shuffle() and permuation()
- When x is an array, both numpy.random.permutation(x) and numpy.random.shuffle(x) can permute the elements in x randomly along the first axis. numpy.random.permutation(x) actually returns a new variable and the original data is not changed. Where as numpy.random.shuffle(x) has changed original data and does not return a new variable.
- Also, permutation can take an int as a parameter and treats it as np.arange(x). Shuffle only takes array_like(array or list) as parameter.

In [61]:
base_array_shuffle = np.arange(10)
print("Shuffling happens in place:-")
for _ in range(3):
    np.random.shuffle(base_array_shuffle)
    print ("Base Array: {}".format(base_array_shuffle))
    print('\n')

print("Permutation returns a copy of the permuted array:-")

base_array_permute = np.arange(10)
for _ in range(3):
    permute_array = np.random.permutation(base_array_permute)
    print ("Permuted Array: {}".format(permute_array))
    print ("Base Array: {}".format(base_array_permute))
#    print(permute_array)
    print('\n')

Shuffling happens in place:-
Base Array: [7 2 4 3 1 6 9 5 8 0]


Base Array: [8 4 7 2 9 6 0 3 5 1]


Base Array: [6 7 9 3 8 5 4 2 0 1]


Permutation returns a copy of the permuted array:-
Permuted Array: [8 2 0 5 3 1 7 9 6 4]
Base Array: [0 1 2 3 4 5 6 7 8 9]


Permuted Array: [3 2 9 8 5 0 4 1 6 7]
Base Array: [0 1 2 3 4 5 6 7 8 9]


Permuted Array: [2 0 1 6 9 7 3 5 8 4]
Base Array: [0 1 2 3 4 5 6 7 8 9]




In [67]:
base_array_1= np.arange(36).reshape(4,3,3)
print("Base Array Shuffle:")
print(base_array_1)
print("Shuffling happens only along the first axis:-")
np.random.shuffle(base_array_1)
print("Base Array After shuffle: ")
print(base_array_1)

base_array_2= np.arange(36).reshape(4,3,3)
print("Base Array Permutation: ")
print(base_array_2)
print("Permutation also happens only along the first axis:-")
permute_array_2 = np.random.permutation(base_array_2)
print("Permuted Array : ")
print(permute_array_2)



Base Array Shuffle:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]]
Shuffling happens only along the first axis:-
Base Array After shuffle: 
[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
Base Array Permutation: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]]
Permutation also happens only along the first axis:-
Permuted Array : 
[[[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


### GENERATOR functions and usage